-- Recreate v_clients view to include new fields and renamed gender column
DROP VIEW IF EXISTS v_clients;

CREATE VIEW v_clients AS
SELECT 
  p.id,
  'client'::text as user_type,
  p.first_name,
  p.last_name,
  p.bio,
  p.profile_photo_url,
  p.location,
  p.tagline,
  p.is_uk_based,
  p.profile_published,
  p.gender,
  p.timezone,
  p.phone_number,
  p.created_at,
  p.updated_at,
  -- Client-specific fields from client_profiles
  cp.primary_goals,
  cp.secondary_goals,
  cp.fitness_goals,
  cp.experience_level,
  cp.preferred_training_frequency,
  cp.preferred_time_slots,
  cp.start_timeline,
  cp.preferred_coaching_style,
  cp.motivation_factors,
  cp.client_personality_type,
  cp.training_location_preference,
  cp.open_to_virtual_coaching,
  cp.budget_range_min,
  cp.budget_range_max,
  cp.budget_flexibility,
  cp.waitlist_preference,
  cp.flexible_scheduling,
  cp.preferred_package_type,
  cp.quiz_completed,
  cp.quiz_answers,
  cp.quiz_completed_at,
  cp.client_survey_completed,
  cp.client_survey_completed_at,
  cp.client_status,
  cp.client_journey_stage,
  cp.journey_progress,
  cp.fitness_equipment_access,
  cp.lifestyle_description,
  cp.lifestyle_other,
  cp.health_conditions,
  cp.has_specific_event,
  cp.specific_event_details,
  cp.specific_event_date,
  cp.trainer_gender_preference,
  cp.discovery_call_preference
FROM profiles p
LEFT JOIN client_profiles cp ON p.id = cp.id
WHERE p.user_type = 'client';