-- Data migration script to populate new trainer_profiles and client_profiles tables
-- This migrates existing data from the profiles table to the new domain-specific tables

-- First, populate trainer_profiles with existing trainer data
INSERT INTO public.trainer_profiles (
  id,
  specializations,
  qualifications,
  certifications,
  experience_years,
  training_philosophy,
  availability_schedule,
  hourly_rate,
  session_rate,
  package_rates,
  before_after_photos,
  testimonials,
  social_media_links,
  preferred_client_goals,
  training_locations,
  equipment_provided,
  languages_spoken,
  max_clients,
  current_client_count,
  profile_setup_completed,
  onboarding_completed,
  terms_agreed,
  terms_agreed_at,
  verification_status,
  verification_requested_at,
  verification_documents,
  admin_verification_notes,
  profile_published,
  published_at,
  last_active_at,
  response_rate,
  average_rating,
  total_reviews,
  profile_completion_percentage,
  streak_count,
  last_profile_update,
  weekly_goal_target,
  monthly_goal_target,
  year_certified,
  created_at,
  updated_at
)
SELECT 
  p.id,
  p.specializations,
  p.qualifications,
  p.certifications,
  p.experience_years,
  p.training_philosophy,
  p.availability_schedule,
  p.hourly_rate,
  p.session_rate,
  p.package_rates,
  p.before_after_photos,
  p.testimonials,
  p.social_media_links,
  p.preferred_client_goals,
  p.training_locations,
  p.equipment_provided,
  p.languages_spoken,
  p.max_clients,
  p.current_client_count,
  p.profile_setup_completed,
  p.onboarding_completed,
  p.terms_agreed,
  p.terms_agreed_at,
  p.verification_status,
  p.verification_requested_at,
  p.verification_documents,
  p.admin_verification_notes,
  p.profile_published,
  p.published_at,
  p.last_active_at,
  p.response_rate,
  p.average_rating,
  p.total_reviews,
  p.profile_completion_percentage,
  p.streak_count,
  p.last_profile_update,
  p.weekly_goal_target,
  p.monthly_goal_target,
  p.year_certified,
  p.created_at,
  p.updated_at
FROM public.profiles p
WHERE p.user_type = 'trainer'
ON CONFLICT (id) DO UPDATE SET
  specializations = EXCLUDED.specializations,
  qualifications = EXCLUDED.qualifications,
  certifications = EXCLUDED.certifications,
  experience_years = EXCLUDED.experience_years,
  training_philosophy = EXCLUDED.training_philosophy,
  availability_schedule = EXCLUDED.availability_schedule,
  hourly_rate = EXCLUDED.hourly_rate,
  session_rate = EXCLUDED.session_rate,
  package_rates = EXCLUDED.package_rates,
  before_after_photos = EXCLUDED.before_after_photos,
  testimonials = EXCLUDED.testimonials,
  social_media_links = EXCLUDED.social_media_links,
  preferred_client_goals = EXCLUDED.preferred_client_goals,
  training_locations = EXCLUDED.training_locations,
  equipment_provided = EXCLUDED.equipment_provided,
  languages_spoken = EXCLUDED.languages_spoken,
  max_clients = EXCLUDED.max_clients,
  current_client_count = EXCLUDED.current_client_count,
  profile_setup_completed = EXCLUDED.profile_setup_completed,
  onboarding_completed = EXCLUDED.onboarding_completed,
  terms_agreed = EXCLUDED.terms_agreed,
  terms_agreed_at = EXCLUDED.terms_agreed_at,
  verification_status = EXCLUDED.verification_status,
  verification_requested_at = EXCLUDED.verification_requested_at,
  verification_documents = EXCLUDED.verification_documents,
  admin_verification_notes = EXCLUDED.admin_verification_notes,
  profile_published = EXCLUDED.profile_published,
  published_at = EXCLUDED.published_at,
  last_active_at = EXCLUDED.last_active_at,
  response_rate = EXCLUDED.response_rate,
  average_rating = EXCLUDED.average_rating,
  total_reviews = EXCLUDED.total_reviews,
  profile_completion_percentage = EXCLUDED.profile_completion_percentage,
  streak_count = EXCLUDED.streak_count,
  last_profile_update = EXCLUDED.last_profile_update,
  weekly_goal_target = EXCLUDED.weekly_goal_target,
  monthly_goal_target = EXCLUDED.monthly_goal_target,
  year_certified = EXCLUDED.year_certified,
  updated_at = EXCLUDED.updated_at;

-- Then, populate client_profiles with existing client data
INSERT INTO public.client_profiles (
  id,
  primary_goals,
  secondary_goals,
  fitness_goals,
  experience_level,
  preferred_training_frequency,
  preferred_time_slots,
  start_timeline,
  preferred_coaching_style,
  motivation_factors,
  client_personality_type,
  training_location_preference,
  open_to_virtual_coaching,
  budget_range_min,
  budget_range_max,
  budget_flexibility,
  waitlist_preference,
  flexible_scheduling,
  preferred_package_type,
  quiz_completed,
  quiz_answers,
  quiz_completed_at,
  client_survey_completed,
  client_survey_completed_at,
  client_status,
  client_journey_stage,
  journey_progress,
  created_at,
  updated_at
)
SELECT 
  p.id,
  p.primary_goals,
  p.secondary_goals,
  p.fitness_goals,
  p.experience_level,
  p.preferred_training_frequency,
  p.preferred_time_slots,
  p.start_timeline,
  p.preferred_coaching_style,
  p.motivation_factors,
  p.client_personality_type,
  p.training_location_preference,
  p.open_to_virtual_coaching,
  p.budget_range_min,
  p.budget_range_max,
  p.budget_flexibility,
  p.waitlist_preference,
  p.flexible_scheduling,
  p.preferred_package_type,
  p.quiz_completed,
  p.quiz_answers,
  p.quiz_completed_at,
  p.client_survey_completed,
  p.client_survey_completed_at,
  p.client_status,
  p.client_journey_stage,
  p.journey_progress,
  p.created_at,
  p.updated_at
FROM public.profiles p
WHERE p.user_type = 'client'
ON CONFLICT (id) DO UPDATE SET
  primary_goals = EXCLUDED.primary_goals,
  secondary_goals = EXCLUDED.secondary_goals,
  fitness_goals = EXCLUDED.fitness_goals,
  experience_level = EXCLUDED.experience_level,
  preferred_training_frequency = EXCLUDED.preferred_training_frequency,
  preferred_time_slots = EXCLUDED.preferred_time_slots,
  start_timeline = EXCLUDED.start_timeline,
  preferred_coaching_style = EXCLUDED.preferred_coaching_style,
  motivation_factors = EXCLUDED.motivation_factors,
  client_personality_type = EXCLUDED.client_personality_type,
  training_location_preference = EXCLUDED.training_location_preference,
  open_to_virtual_coaching = EXCLUDED.open_to_virtual_coaching,
  budget_range_min = EXCLUDED.budget_range_min,
  budget_range_max = EXCLUDED.budget_range_max,
  budget_flexibility = EXCLUDED.budget_flexibility,
  waitlist_preference = EXCLUDED.waitlist_preference,
  flexible_scheduling = EXCLUDED.flexible_scheduling,
  preferred_package_type = EXCLUDED.preferred_package_type,
  quiz_completed = EXCLUDED.quiz_completed,
  quiz_answers = EXCLUDED.quiz_answers,
  quiz_completed_at = EXCLUDED.quiz_completed_at,
  client_survey_completed = EXCLUDED.client_survey_completed,
  client_survey_completed_at = EXCLUDED.client_survey_completed_at,
  client_status = EXCLUDED.client_status,
  client_journey_stage = EXCLUDED.client_journey_stage,
  journey_progress = EXCLUDED.journey_progress,
  updated_at = EXCLUDED.updated_at;