-- Corrected data migration script using actual table columns
-- Migrate existing trainer data to trainer_profiles
INSERT INTO public.trainer_profiles (
  id,
  specializations,
  qualifications,
  year_certified,
  hourly_rate,
  availability_schedule,
  max_clients,
  verification_status,
  verification_requested_at,
  verification_documents,
  admin_verification_notes,
  testimonials,
  profile_setup_completed,
  terms_agreed,
  created_at,
  updated_at
)
SELECT 
  p.id,
  p.specializations,
  p.qualifications,
  p.year_certified,
  p.hourly_rate,
  p.availability_schedule,
  p.max_clients,
  p.verification_status,
  p.verification_requested_at,
  p.verification_documents,
  p.admin_verification_notes,
  p.testimonials,
  p.profile_setup_completed,
  p.terms_agreed,
  p.created_at,
  p.updated_at
FROM public.profiles p
WHERE p.user_type = 'trainer'
ON CONFLICT (id) DO UPDATE SET
  specializations = EXCLUDED.specializations,
  qualifications = EXCLUDED.qualifications,
  year_certified = EXCLUDED.year_certified,
  hourly_rate = EXCLUDED.hourly_rate,
  availability_schedule = EXCLUDED.availability_schedule,
  max_clients = EXCLUDED.max_clients,
  verification_status = EXCLUDED.verification_status,
  verification_requested_at = EXCLUDED.verification_requested_at,
  verification_documents = EXCLUDED.verification_documents,
  admin_verification_notes = EXCLUDED.admin_verification_notes,
  testimonials = EXCLUDED.testimonials,
  profile_setup_completed = EXCLUDED.profile_setup_completed,
  terms_agreed = EXCLUDED.terms_agreed,
  updated_at = EXCLUDED.updated_at;

-- Migrate existing client data to client_profiles  
INSERT INTO public.client_profiles (
  id,
  primary_goals,
  secondary_goals,
  fitness_goals,
  experience_level,
  preferred_training_frequency,
  preferred_time_slots,
  start_timeline,
  preferred_coaching_style,
  motivation_factors,
  client_personality_type,
  training_location_preference,
  open_to_virtual_coaching,
  budget_range_min,
  budget_range_max,
  budget_flexibility,
  waitlist_preference,
  flexible_scheduling,
  preferred_package_type,
  quiz_completed,
  quiz_answers,
  quiz_completed_at,
  client_survey_completed,
  client_survey_completed_at,
  client_status,
  client_journey_stage,
  journey_progress,
  created_at,
  updated_at
)
SELECT 
  p.id,
  p.primary_goals,
  p.secondary_goals,
  p.fitness_goals,
  p.experience_level,
  p.preferred_training_frequency,
  p.preferred_time_slots,
  p.start_timeline,
  p.preferred_coaching_style,
  p.motivation_factors,
  p.client_personality_type,
  p.training_location_preference,
  p.open_to_virtual_coaching,
  p.budget_range_min,
  p.budget_range_max,
  p.budget_flexibility,
  p.waitlist_preference,
  p.flexible_scheduling,
  p.preferred_package_type,
  p.quiz_completed,
  p.quiz_answers,
  p.quiz_completed_at,
  p.client_survey_completed,
  p.client_survey_completed_at,
  p.client_status,
  p.client_journey_stage,
  p.journey_progress,
  p.created_at,
  p.updated_at
FROM public.profiles p
WHERE p.user_type = 'client'
ON CONFLICT (id) DO UPDATE SET
  primary_goals = EXCLUDED.primary_goals,
  secondary_goals = EXCLUDED.secondary_goals,
  fitness_goals = EXCLUDED.fitness_goals,
  experience_level = EXCLUDED.experience_level,
  preferred_training_frequency = EXCLUDED.preferred_training_frequency,
  preferred_time_slots = EXCLUDED.preferred_time_slots,
  start_timeline = EXCLUDED.start_timeline,
  preferred_coaching_style = EXCLUDED.preferred_coaching_style,
  motivation_factors = EXCLUDED.motivation_factors,
  client_personality_type = EXCLUDED.client_personality_type,
  training_location_preference = EXCLUDED.training_location_preference,
  open_to_virtual_coaching = EXCLUDED.open_to_virtual_coaching,
  budget_range_min = EXCLUDED.budget_range_min,
  budget_range_max = EXCLUDED.budget_range_max,
  budget_flexibility = EXCLUDED.budget_flexibility,
  waitlist_preference = EXCLUDED.waitlist_preference,
  flexible_scheduling = EXCLUDED.flexible_scheduling,
  preferred_package_type = EXCLUDED.preferred_package_type,
  quiz_completed = EXCLUDED.quiz_completed,
  quiz_answers = EXCLUDED.quiz_answers,
  quiz_completed_at = EXCLUDED.quiz_completed_at,
  client_survey_completed = EXCLUDED.client_survey_completed,
  client_survey_completed_at = EXCLUDED.client_survey_completed_at,
  client_status = EXCLUDED.client_status,
  client_journey_stage = EXCLUDED.client_journey_stage,
  journey_progress = EXCLUDED.journey_progress,
  updated_at = EXCLUDED.updated_at;