-- Update v_trainers view to include new Ways of Working fields
DROP VIEW IF EXISTS v_trainers;

CREATE VIEW v_trainers AS
SELECT 
  p.id,
  p.created_at,
  p.updated_at,
  p.first_name,
  p.last_name,
  p.bio,
  p.profile_photo_url,
  p.location,
  p.tagline,
  p.is_uk_based,
  p.profile_published,
  p.profile_image_position,
  p.wow_how_i_work,
  p.wow_what_i_provide,
  p.wow_client_expectations,
  p.wow_activities,
  p.wow_activity_assignments,
  p.wow_visibility,
  p.wow_setup_completed,
  tp.specializations,
  tp.qualifications,
  tp.certifying_body,
  tp.year_certified,
  tp.uploaded_certificates,
  tp.hourly_rate,
  tp.package_options,
  tp.availability_schedule,
  tp.max_clients,
  tp.works_bank_holidays,
  tp.verification_status,
  tp.verification_requested_at,
  tp.verification_documents,
  tp.admin_verification_notes,
  tp.is_verified,
  tp.rating,
  tp.total_ratings,
  tp.free_discovery_call,
  tp.offers_discovery_call,
  tp.discovery_call_price,
  tp.calendar_link,
  tp.testimonials,
  tp.training_types,
  tp.delivery_format,
  tp.communication_style,
  tp.coaching_style,
  tp.client_preferences,
  tp.ideal_client_personality,
  tp.ideal_client_types,
  tp.video_checkins,
  tp.messaging_support,
  tp.weekly_programming_only,
  tp.ways_of_working_onboarding,
  tp.ways_of_working_first_week,
  tp.ways_of_working_ongoing,
  tp.ways_of_working_tracking,
  tp.ways_of_working_expectations,
  tp.ways_of_working_what_i_bring,
  tp.profile_setup_completed,
  tp.terms_agreed,
  tp.how_started,
  tp.philosophy,
  tp.professional_milestones
FROM profiles p
JOIN trainer_profiles tp ON p.id = tp.id
WHERE p.user_type = 'trainer';