-- Add missing columns to v_trainers view
DROP VIEW IF EXISTS public.v_trainers;

CREATE VIEW public.v_trainers AS
SELECT 
  p.id,
  p.created_at,
  p.updated_at,
  p.first_name,
  p.last_name,
  p.bio,
  p.profile_photo_url,
  p.location,
  p.user_type,
  p.client_status,
  p.client_journey_stage,
  p.client_survey_completed,
  p.client_survey_completed_at,
  p.client_personality_type,
  p.preferred_training_frequency,
  p.preferred_time_slots,
  p.training_location_preference,
  p.preferred_package_type,
  p.preferred_coaching_style,
  p.primary_goals,
  p.tagline,
  p.is_uk_based,
  p.profile_published,
  p.consent_marketing,
  p.consent_service,
  p.consent_timestamp,
  p.consent_version,
  p.privacy_policy_version,
  p.marketing_unsubscribed_at,
  p.terms_agreed,
  p.profile_setup_completed,
  p.profile_image_position,
  -- Trainer-specific fields from trainer_profiles
  tp.verification_status,
  tp.is_verified,
  tp.verification_requested_at,
  tp.verification_documents,
  tp.admin_verification_notes,
  tp.specializations,
  tp.qualifications,
  tp.training_types,
  tp.delivery_format,
  tp.communication_style,
  tp.coaching_style,  -- Add this missing column
  tp.ideal_client_types,  -- Add this missing column
  tp.philosophy,
  tp.how_started,
  tp.hourly_rate,
  tp.package_options,
  tp.offers_discovery_call,
  tp.free_discovery_call,
  tp.discovery_call_price,
  tp.calendar_link,
  tp.messaging_support,
  tp.video_checkins,
  tp.weekly_programming_only,
  tp.max_clients,
  tp.availability_schedule,
  tp.works_bank_holidays,
  tp.ways_of_working_onboarding,
  tp.ways_of_working_first_week,
  tp.ways_of_working_expectations,
  tp.ways_of_working_tracking,
  tp.ways_of_working_ongoing,
  tp.ways_of_working_what_i_bring,
  tp.testimonials,
  tp.uploaded_certificates,
  tp.professional_milestones,
  tp.year_certified,
  tp.certifying_body,
  tp.rating,
  tp.total_ratings
FROM profiles p
LEFT JOIN trainer_profiles tp ON p.id = tp.id
WHERE p.user_type = 'trainer';