// This file is automatically generated. Do not edit it directly.
// NOTE: This file is environment-specific. Dev project uses dev Supabase, prod uses prod Supabase.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkzahqnsfjnvskfywbvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpremFocW5zZmpudnNrZnl3YnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwMDM2NzAsImV4cCI6MjA4MDU3OTY3MH0.MdDuqQdFKXkZOqf0BuXQRFyWAI6ugrBmnqr2wMf31AY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
